# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CalgaryUrbanite
email: derek@calgaryurbanite.com
description: > # this means to ignore newlines until "baseurl:"
  CalgaryUrbanite is an urban / sustainability / social / web blogazine.
keywords: "calgary, urbanite, calgary, alberta, local, events, sustainable, living, reviews, rants, community, blog, #yyc, twitter, dmcb, dmcb design, dmcbdesign"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://old.calgaryurbanite.com" # the base hostname & protocol for your site
twitter_username: derekmcb
github_username:  dmcb

# Build settings
markdown: kramdown
source: src
destination: _site
permalink: /post/:title/